name: Bug Report
description: Report incorrect behavior in this module
title: "BUG: "
labels: [bug]

body:
  - type: checkboxes
    id: checks
    attributes:
      label: module version checks
      options:
        - label: >
            I have checked that this issue has not already been reported.
          required: true
  - type: textarea
    id: problem
    attributes:
      label: Issue Description
      description: >
        Please provide a description of the issue shown in the reproducible example.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: >
        Please describe or show a code example of the expected behavior.
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Installed Versions
      placeholder: >
        % sudo /usr/local/nginx/sbin/nginx -V
        nginx version: nginx/1.27.0
        built by gcc 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04) 
        configure arguments: --add-module=../nginx-module-vts
      description: >	
        Please paste the output of ``nginx -V``
      value: >
        <details>


        Replace this line with the output of nginx -V


        </details>
    validations:
      required: true
  - type: textarea
    id: conf
    attributes:
      label: Reproducible Example nginx.conf
      description: >	
        Please paste the reproducible nginx.conf
